### ISSUE TITLE
figure out how to use disa's kmeans++

### ISSUE THREAD

**Issue by jovo** [neurodata/meda#12]
@disa-mhembere little help?

**Comment by disa-mhembere** [comment]
using it from within flashR?

**Comment by MrAE** [comment]
I'm just using regular R at the moment, but I could move to using flashR.

**Comment by disa-mhembere** [comment]
There is a version in flashGraphR which is not the fastest, but faster than
anything else you'll use. I have no higher level interface for the newest
stuff and will not add it to flashR so this might be your best option.

```
library(devtools)
install_github("flashxio/FlashGraphR")
?fg.kmeans
```
