### ISSUE TITLE
install bug :(

### ISSUE THREAD

**Issue by jovo** [neurodata/meda#19]
when i type:

`devtools::install_github("neurodata/meda")`

i get:

`Error: Could not find build tools necessary to build data.table`

turns out, i needed to install Xcode more.  also, i didn't have devtools, so i needed to install that.

please update readme with software dependencies

**Comment by jovo** [comment]
i installed Xcode.  still have the same problem :(

**Comment by MrAE** [comment]
Fixed by installing in R from command line.  Seems to be a problem with RStudio and Xcode command line tools perhaps?
