### ISSUE TITLE
let's make the webpage link to both the R and Python versions?

### ISSUE THREAD

**Issue by jovo** [neurodata/meda#6]
@MrAE assign to ryan?

**Comment by MrAE** [comment]
Sure, 

@rmarren1 the webpage is in the `gh-pages` branch.  You can copy the `index.html` to `r.html` and add a `py.html` and modify `index.html` to point to both. For now, you can create an issue in rmarren1/meda and make pull requests.  If you have any questions don't hesitate to ask.

@jovo ?
