### ISSUE TITLE
Enhancement checklist 

### ISSUE THREAD

**Issue by MrAE** [neurodata/meda#9]
| Plot section | task | status | 
|:---:|:-------------------------------------------------------------------:|---|
| 1   | OK!  |  ✅ |
| 2a   | sort; hclust  | ✅ |
| 2b   | sort hclust button  | :x: |
| 2c   | color code hclust labels  | :x: |
| 3   | turn violin on/off button  | :x: |
| 4   | sort by label button (show boxes around groups button)  | :x: |
| 5   | color by label button  | ❌  |
| 6   | ok!  | ✅  |
| 7   | too many points; ggplot geom_hex  | ✅ |
| 8   | ok!  | ✅ |
| 9   | rescale points inversely with n  | ✅ |
| 10  | ok!  | ✅  |
| 11  | scree plot (like 6)  | ✅  |
| 12  | scatter plot 3d pca on correlation matrix button color by label  | ✅ |
| 13  | means per cluster (heatmap) [sort by label](http://docs.neurodata.io/synaptome-stats/Code/SynapseExploration.html#heat-maps-lv-1) & distances  | :x: | button
| 14  | correlations per cluster (heatmap) & distances  | :x: |
| 15  | jittered scatterplot by cluster  | ✅  |
| 16  | lda vs \hat{d} w/ resubstitution   | :x: |
| 17  | lda decision boundaries overlaid on 10  | :x: |

## Legend
| symbol | meaning |
|:-------:|----------|
|  ❌     | Not done |
|  ✅ | Jesse updated to first iteration |

![96222e6a-4785-49fe-bbba-72de00986a88](https://cloud.githubusercontent.com/assets/6886669/21645920/0751120a-d262-11e6-88da-063b5ec9c301.JPG)

**Comment by jovo** [comment]
this is awesome!

**Comment by MrAE** [comment]
for later https://plot.ly/ggplot2/ggdendro-dendrograms/

**Comment by MrAE** [comment]
Trajectory has changed.  Closing.
